# Generated by Django 4.0.6 on 2023-01-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
    ]
